<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject Condition="'$(MSBuildProjectName)' != 'ProdTrack.TestSupport'">true</IsTestProject>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'ProdTrack.TestSupport'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="AwesomeAssertions" />
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
  </ItemGroup>
</Project>
